octopus/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout, name='logout'),
]

octopus/api/urls.py
from django.urls import path
from .views import ProductsList, ProductsDetail, InventoryList, InventoryDetail

urlpatterns = [
    path('products/<int:pk>/', ProductsDetail.as_view()),
    path('products/', ProductsList.as_view()),
    path('inventory/<int:pk>/', InventoryDetail.as_view()),
    path('inventory/', InventoryList.as_view()),
]

octopus/octopus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

octopus/staticpages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cad_func/', views.cad_func, name='cad_func'),
    path('cad_prod/', views.cad_prod, name='cad_prod'),
    path('entrada/', views.entrada, name='entrada'),
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('saida/', views.saida, name='saida'),
]

octopus/warehouse/urls.py
from django.urls import path

from . import views

app_name = 'warehouse'
urlpatterns = [
    path('', views.list_products, name='index'),
    path('cad_prod/', views.create_product, name='cad_prod'),
    path('cad_func/', views.create_employee, name='cad_func'),
    path('entrada/', views.update_product, name="entrada"),
    path('saida/', views.update_product2, name="saida"),
    path('historico/<int:bar_code>/', views.history, name='history')
]

octopus/staticpages/models.py
from django.db import models

# Create your models here.

octopus/staticpages/views.py
from django.shortcuts import render

# Create your views here.

def cad_func(request):
    context= {}
    return render(request, 'staticpages/cad_func.html', context)

def cad_prod(request):
    context= {}
    return render(request, 'staticpages/cad_prod.html', context)

def entrada(request):
    context= {}
    return render(request, 'staticpages/entrada.html', context)

def index(request):
    context= {}
    return render(request, 'staticpages/index.html', context)

def login(request):
    context= {}
    return render(request, 'staticpages/login.html', context)

def saida(request):
    context= {}
    return render(request, 'staticpages/saida.html', context)

octopus/staticpages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% block css %}{% endblock css %}">
    <title>
        {% block title %}{% endblock title %} | Octopus
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="../static/logo_octopus.png" alt="" id="logo" width="40">
            </a>
          <a class="navbar-brand" id="warehouse" href="{% url 'warehouse:index' %}">Estoque</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Produtos
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'warehouse:cad_prod' %}">Cadastrar Produto</a></li>
                      <li><a class="dropdown-item" href="{% url 'warehouse:entrada' %}">Entrada</a></li>
                      <li><a class="dropdown-item" href="{% url 'warehouse:saida' %}">Saída</a></li>
                    </ul>
                </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Funcionário
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'warehouse:cad_func' %}">Cadastrar Funcionário</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% block user %}{% endblock user %}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid" id="barra">
        <a href="#" class="link-success">Warehouse</a>
        <div class="list-group">
            {% block main_button %}{% endblock main_button %}
        </div>
      </div>
      {% block content %}
      {% endblock content %}










<!--
    <header id="cabecalho-principal">
        <a href="{% url 'warehouse:index' %}">
            <p>Octopus</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'cad_func' %}">Employee Register</a></li>
                <li><a href="{% url 'warehouse:cad_prod' %}">Product Register</a></li>
                <li><a href="{% url 'entrada' %}">New Supply</a></li>
                <li><a href="{% url 'index' %}">Inventory</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'saida' %}">New Order</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
-->
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>