octopus/api/urls.py
from django.urls import path
from .views import ProductsList, ProductsDetail, InventoryList, InventoryDetail

urlpatterns = [
    path('products/<int:pk>/', ProductsDetail.as_view()),
    path('products/', ProductsList.as_view()),
    path('inventory/<int:pk>/', InventoryDetail.as_view()),
    path('inventory/', InventoryList.as_view()),
]

octopus/octopus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('warehouse/', include('warehouse.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

octopus/warehouse/urls.py
from django.urls import path

from . import views

app_name = 'warehouse'
urlpatterns = [
    path('', views.list_products, name='index'),
    path('cad_prod/', views.create_product, name='cad_prod'),
    path('cad_func/', views.create_employee, name='cad_func'),
    path('entrada/', views.update_product, name="entrada"),
    path('saida/', views.update_product2, name="saida"),
    path('historico/<int:bar_code>/', views.history, name='history')
]

octopus/warehouse/models.py
from django.db import models
from django.conf import settings


class Products(models.Model):
    name = models.CharField(max_length=255)
    bar_code = models.CharField(max_length=255)
    qtt = models.IntegerField(default= 0)
    img= models.ImageField()

    def __str__(self):
        return f'{self.name} ({self.qtt})'


class Sails(models.Model):
    bar_code = models.CharField(max_length=255)
    qtt = models.IntegerField(default=0)
    id_ML = models.CharField(max_length=255)

    def __str__(self):
        return f'"{self.id_ML}" - {self.bar_code}: {self.qtt}'

class Employees(models.Model):
    id_e= models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    img_e= models.ImageField()

    def __str__(self):
        return f'"{self.name}" - {self.position}. Senha: {self.password}'

class Inventory(models.Model):
    sail = models.ForeignKey(Sails, on_delete=models.CASCADE, null= True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)
    qtt= models.IntegerField(default=0)
    mov= models.CharField(max_length= 255)
    date = models.DateTimeField(auto_now= True)

    def __str__(self):
        return f'"Código de venda nº {self.sail}" do produto {self.product} feita pelo funcionário {self.employee} em {self.date}'

octopus/warehouse/views.py
from django.shortcuts import render
from .models import Products, Employees, Inventory
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test

def not_in_estoquista_group(user):
    if user:
        return user.groups.filter(name='Estoquista').count() == 0
    return False

# Create your views here.
@login_required
def list_products(request):
    print(request.user.first_name)
    e = get_object_or_404(Employees, id_e= request.user.username)
    p= Products.objects.all()
    i= Inventory.objects.all()
    context= {'products_list': p, 'employee': e, 'inventory_list': i}
    return render(request, 'warehouse/index.html', context)

@login_required
def create_product(request):
    e = get_object_or_404(Employees, id_e= request.user.username)
    if request.method == 'POST':
        product_name = request.POST['name']
        product_code= request.POST['bar_code']
        product_qtt = request.POST['qtt']
        product_img= request.FILES['img']
        fss = FileSystemStorage()
        file = fss.save(product_img.name, product_img)
        file_url = fss.url(file)
        p = Products(name=product_name, bar_code= product_code, qtt=product_qtt, img= file_url)
        p.save()
        i= Inventory(product= p, employee= e, qtt= product_qtt, mov= 'E')
        i.save()
        return HttpResponseRedirect(reverse('warehouse:index'))
    else:
        context= {'employee': e}
        return render(request, 'warehouse/cad_prod.html', context)

#New Products Supply
@login_required
def update_product(request):
    e = get_object_or_404(Employees, id_e= request.user.username)
    if request.method == 'POST':
        product_code= request.POST['bar_code']
        product_qtt = request.POST['qtt']
        p = get_object_or_404(Products, bar_code= product_code)
        p.bar_code= product_code
        p.qtt= p.qtt + int(product_qtt)
        p.save()
        i= Inventory(product= p, employee= e, qtt= product_qtt, mov= 'E')
        i.save()
        return HttpResponseRedirect(reverse('warehouse:index'))
    else:
        context= {'employee': e}
        return render(request, 'warehouse/entrada.html', context)

#New Product Order
@login_required
def update_product2(request):
    e = get_object_or_404(Employees, id_e= request.user.username)
    if request.method == 'POST':
        product_code= request.POST['bar_code']
        product_qtt = request.POST['qtt']
        p = get_object_or_404(Products, bar_code= product_code)
        p.qtt= p.qtt - int(product_qtt)
        p.save()
        i= Inventory(product= p, employee= e, qtt= product_qtt, mov= 'S')
        i.save()
        return HttpResponseRedirect(reverse('warehouse:index'))
    else:
        context= {'employee': e}
        return render(request, 'warehouse/saida.html', context)

@login_required
@user_passes_test(not_in_estoquista_group, login_url='warehouse:index')
def create_employee(request):
    e2 = get_object_or_404(Employees, id_e= request.user.username)
    if request.method == 'POST':
        employee_name = request.POST['name']
        employee_id= request.POST['id_e']
        employee_position = request.POST['position']
        employee_password = request.POST['password']
        employee_img= request.FILES['img_e']
        print("\n\nValor do radio é: " + employee_position + "\n\n")
        if employee_position == '1':
            employee_position= " "
            employee_position= "Estoquista"
        if employee_position == '2':
            employee_position= " "
            employee_position= "Gestor de estoque"
        fss = FileSystemStorage()
        file = fss.save(employee_img.name, employee_img)
        file_url = fss.url(file)
        user= User.objects.filter(username= employee_id).first()
        if user:
            return HttpResponseRedirect(reverse('warehouse:cad_func'))
        else:
            user= User.objects.create_user(username= employee_id, first_name= employee_name, password= employee_password)
            user.save()
            user_group= Group.objects.get(name= employee_position)
            user.groups.add(user_group)
            e = Employees(id_e= employee_id, name= employee_name, position= employee_position, password= employee_password, img_e= file_url)
            e.save()
            return HttpResponseRedirect(reverse('warehouse:index'))
    else:
        context= {'employee': e2}
        return render(request, 'warehouse/cad_func.html', context)

@login_required
def history(request, bar_code):
    e = get_object_or_404(Employees, id_e= request.user.username)
    p = get_object_or_404(Products, bar_code= bar_code)
    i = Inventory.objects.filter(product= p.id)
    #print("\n\n", i[2].mov, "\n\n")
    context= {'employee': e, 'inventory_list': i}
    return render(request, 'warehouse/historico.html', context)

'''
def search_products(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        products_list = product.objects.filter(name__icontains=search_term)
        context = {"products_list": products_list}
    return render(request, 'products/search.html', context)
'''

octopus/warehouse/templates/warehouse/entrada.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Movimentar Estoque {% endblock title %}
{% block css %} {% static 'style.css' %} {% endblock css %}
{% block main_button %} <button type="submit" form="update_product" class="list-group-item"> SALVAR </button> {% endblock main_button %}
{% block user %} 
  {% if employee.position == 'Gestor de estoque' %}
    {{ employee.name }} (ge)
  {% else %}
    {{ employee.name }} (es)
  {% endif %}
{% endblock user %}
{% block content %}

<div class="formbold-main-wrapper">
    <!-- Author: FormBold Team -->
    <!-- Learn More: https://formbold.com -->
    <div class="formbold-form-wrapper">
      <form id="update_product" enctype="multipart/form-data" action="{% url 'warehouse:entrada' %}" method="POST">
        {% csrf_token %}
          <div class="formbold-input-flex">
            <div>
                <input
                type="text"
                name="bar_code"
                id="lastname"
                placeholder="Código de barras"
                class="formbold-form-input"
                />
                <label for="lastname" class="formbold-form-label"> Código de barras </label>
            </div>
            <div>
                <input
                type="number"
                name="qtt"
                id="lastname"
                class="formbold-form-input"
                min="1"
                />
                <label for="lastname" class="formbold-form-label"> Quantidade </label>
            </div>
          </div>
      </form>
    </div>
  </div>

{% endblock content %}

octopus/warehouse/templates/warehouse/historico.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Histórico de Movimentações {% endblock title %}
{% block css %} {% static 'style.css' %} {% endblock css %}
{% block main_button %} <a href="{% url 'warehouse:cad_prod' %}" class="list-group-item">CADASTRAR</a> {% endblock main_button %}
{% block user %} 
  {% if employee.position == 'Gestor de estoque' %}
    {{ employee.name }} (ge)
  {% else %}
    {{ employee.name }} (es)
  {% endif %}
{% endblock user %}
{% block content %}
<br>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Código de Barras</th>
        <th scope="col">Produto</th>
        <th scope="col">Quantidade</th>
        <th scope="col">Movimentação</th>
        <th scope="col">Nome do funcionário</th>
        <th scope="col">Data</th>
      </tr>
    </thead>
    <tbody>
      {% if inventory_list  %}
        {% for inventory in inventory_list %}
          {% if inventory.mov == 'S' %}
            <tr class="table-danger">
          {% endif %}
          {% if inventory.mov == 'E' %}
            <tr class="table-success">
          {% endif %}   
            <th scope="row">{{ inventory.product.bar_code }}</th>
            <td>{{ inventory.product.name }}</td>
            <td>{{ inventory.qtt }}</td>
            <td>{{ inventory.mov }}</td>
            <td>{{ inventory.employee.name }}</td>
            <td>{{ inventory.date }}</td>
            </tr>
        {% endfor %}
      {% endif %}
    </tbody>
  </table>
{% endblock content %}

octopus/warehouse/templates/warehouse/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Estoque {% endblock title %}
{% block css %} {% static 'style.css' %} {% endblock css %}
{% block main_button %} <a href="{% url 'warehouse:cad_prod' %}" class="list-group-item">CADASTRAR</a> {% endblock main_button %}
{% block user %} 
  {% if employee.position == 'Gestor de estoque' %}
    {{ employee.name }} (ge)
  {% else %}
    {{ employee.name }} (es)
  {% endif %}
{% endblock user %}
{% block content %}
{% if products_list %}
<div class="container">
    {% for product in products_list %}
    <!-- Card 1 -->
    <a href="{% url 'warehouse:history' bar_code=product.bar_code %}" style="text-decoration: none">
    <div class="card card-1">
      <!-- card-header -->
      <div class="card-header">
        <img src="{{product.img}}" class="card-img" />
      </div>
      <!-- card-header -->

      <!-- card-body -->
      <div class="card-body">
        <h3 class="card-titulo">{{ product.name }}</h3>
        <h2 class="card-titulo">{{ product.bar_code }}</h2>
        <p class="card-titulo">
            {{ product.qtt }} unidade(s)
        </p>
      </div>
      <!-- card-body -->
    </div>
    </a>
    {% endfor %}
{% else %}
    <br><br>
    <h1 style="text-align: center">Não foi encontrado nenhum Produto.</h1>
{% endif %}
{% endblock content %}

octopus/warehouse/templates/warehouse/saida.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Movimentar Estoque {% endblock title %}
{% block css %} {% static 'style.css' %} {% endblock css %}
{% block main_button %} <button type="submit" form="update_product" class="list-group-item" style="background-color: red"> SALVAR </button> {% endblock main_button %}
{% block user %} 
  {% if employee.position == 'Gestor de estoque' %}
    {{ employee.name }} (ge)
  {% else %}
    {{ employee.name }} (es)
  {% endif %}
{% endblock user %}
{% block content %}

<div class="formbold-main-wrapper">
    <!-- Author: FormBold Team -->
    <!-- Learn More: https://formbold.com -->
    <div class="formbold-form-wrapper">
      <form id="update_product" enctype="multipart/form-data" action="{% url 'warehouse:saida' %}" method="POST">
        {% csrf_token %}
          <div class="formbold-input-flex">
            <div>
                <input
                type="text"
                name="bar_code"
                id="lastname"
                placeholder="Código de barras"
                class="formbold-form-input"
                />
                <label for="lastname" class="formbold-form-label"> Código de barras </label>
            </div>
            <div>
                <input
                type="number"
                name="qtt"
                id="lastname"
                class="formbold-form-input"
                min="1"
                />
                <label for="lastname" class="formbold-form-label"> Quantidade </label>
            </div>
          </div>
      </form>
    </div>
  </div>

{% endblock content %}